language: python
python:
  - '3.7'
branches:
  only:
    - source
install:
  - pip install pelican markdown typogrify
script:
  - make publish
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: source
  local_dir: output
  target_branch: master
